name: Pylint check for haberdashery
on:
  push:
    branches: [main]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install pylint
      - name: Run pylint check
        run: |
          pylint --disable=all --enable=spelling --spelling-dict=en_US --spelling-private-dict-file=./custom_dict.txt ./ | tee pylint_report.txt
          cat pylint_report.txt | grep -i "haberdashery"